# Set the base image according to the selected device
# FROM nvidia/cuda:11.4.0-cudnn8-runtime-ubuntu20.04
# TODO: Experiment using this base image instead
FROM ghcr.io/pytorch/pytorch-nightly

# Set the working directory
WORKDIR /app

COPY ./docker/packages-apt.txt .

# Install any additional system packages needed
RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    git \
    cmake \
    && rm -rf /var/lib/apt/lists/*
RUN apt-get update && xargs -a packages-apt.txt apt-get install -y


# Copy requirements.txt into the container
COPY ./docker/packages-python3.txt .

# Install any additional Python packages needed
RUN pip install --no-cache-dir -r packages-python3.txt

# Copy the rest of the application code into the container
COPY . .

# Set the entrypoint command
ENTRYPOINT ["/app/entrypoint.sh"]
